name: osiguranje11082017_v3
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Dzenana <email@example.com>

environment:
  sdk: '1.24.2'

dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: ^0.2.2
  font_awesome: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  firebase: '^4.0.0'
  dson: ^0.3.0

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
