import 'package:osiguranje11082017_v3/Osiguranje/osiguranjeclass.dart';


List<OsiguranjeClass> osiguranja = [

  new OsiguranjeClass()
    ..naziv = "Osiguranje imovine"
    ..opis = "Vaša privatna kao i poslovna imovina izložena je različitim nepredvidivim događajima koja mogu  znatno uticati  na smanjenje njene vrijednosti."
    ..tip = "imovina"
    ..id = 1
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",

  new OsiguranjeClass()
    ..naziv = "Osiguranje motornih vozila"
    ..opis = "Obavezno osiguranje vlasnika odnosno korisnika motornog vozila je obavezno zakonsko osiguranje od odgovornosti za štete pričinjene trećim osobama."
    ..tip = "auto"
    ..id = 2
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",

  new OsiguranjeClass()
    ..naziv = "Putničko zdravstveno osiguranje"
    ..opis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
    ..tip = "zivot"
    ..id = 3
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",
  new OsiguranjeClass()
    ..naziv = "Osiguranje nezgode"
    ..opis = "Osiguranje nezgode je osiguranje koje pokriva štetu nastalu usljed nezgode, to je vrsta osiguranja osobe od iznenadnih i nepredvidljivih događaja."
    ..tip = "zivot"
    ..id = 4
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",
  new OsiguranjeClass()
    ..naziv = "Osiguranje transporta"
    ..opis = "Roba je u svakom slučaju izložena određenim rizicima. A kada se roba transportuje  onda se ti rizici multipliciraju. Duga putovanja, utovari, pretovari, istovari, različita prijevozna sredstva, loše vrijeme, krađe, fizička oštećenja samo su neki rizici kojima može biti izložena roba u transportu."
    ..tip = "auto"
    ..id = 5
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",
  new OsiguranjeClass()
    ..naziv = "Životno osiguranje"
    ..opis = "Osiguranjem onoga što je najvrijednije – Vašeg života i života vaših najbližih - dobivate oslonac za sigurniju budućnost. Osigurajte svoj život i učinite budućnost manje neizvjesnom!"
    ..tip = "zivot"
    ..id = 6
    ..duziOpis = "Planiranje putovanja je često kompleksan posao. Kada planiramo putovanje, pogotovo u inostranstvo potrebno je da se zapitamo šta ako nam se nešto desi?"
        "Ako se iznenada u inostranstvu razbolimo ili pretrpimo povredu?"
        "Ako nam je neophodna medicinska pomoć?"
        "Kome ćemo se u takvim momentima  obratiti?"
        "Znamo da su zdravstvene usluge u inostranstvu jako skupe."
        "Kako ćemo platiti troškove liječenja ?"
        "Kada putujemo sa osobnim vozilom često nas na granici pitaju za ''Zeleni karton''  jer se podrazumjeva da smo osigurani za slučaj da našim vozilom nanesemo neku štetu."
        "Međutim da li smo osigurali ono što je važnije? Zapravo, ono što je 'najvažnije''- NAŠE ZDRAVLJE?"
        "Za to nam služi polica Putničkog zdravstvenog osiguranja"
        "Za sve, koji za vrijeme boravka u inostranstvu žele imati:"
        "Kvalitetno i pouzdano osiguranje koje je dostupno 24 sata i 365 dana u godini"
        "Koje će Vas brzo i efikasno zbrinuti ako Vam se desi nepredviđena zdravstvena neprilika."
        "Koje će fleksibilo riješiti Vaš odštetni zahtjev u maksimalno brzom roku i refundirati novac koji ste platili za ljekarske usluge, lijekove, prevoz ambulantnih vozila pa čak i troškove repatrijacije ukoliko osigurana osoba umre u inostranstvu ili ako se osiguranik ne može vratiti sam uslijed osiguranog slučaja u mjesto prebivališta."
        "Koje će za Vas garantirati i platiti iznos u Vaše ime."
        "Svi državljani Bosne i Hercegovine koji u inostranstvo putuju, sa BH pasošom u države sa kojima postoje vizne odredbe, uvjetovani su da uz zahtjev za izdavanje vize prilože policu Putničkog zdravstvenog osiguranja. Na tržištu se nude razne police Putničkog zdravstvenog osiguranja koje konzularno diplomatska predstavništva prihvataju, međutim ako dođe do osiguranog slučaja često nastaju komplikacije i teškoće kod naplate!"
        "Ne dozvolite da vas vuku za rukav, raspitajte se!"
        "Pitajte - dobro je znati:"
        "Da li je Vaše osiguranje ima asistenta u inostranstvu koji će Vam na maternjem jeziku pružiti uslugu 24 sata-365 dana u godini ako Vam se nešto desi i koja je njegova reputacija?"
        "Za koliko vremena će osiguranje riješiti vaš odštetni zahtjev?"
        "Koliko dugo ćete čekati da Vam se isplati šteta?"
        "Putovanja su puna iznenađenja, neka iznenađenja ne možemo predvidjeti i spriječiti."
        "Svjedočenja naših osiguranika iz hronike šteta Sarajevo osiguranja"
        "Uplatili smo preko turističke agencije za cijelu familiju godišnji odmor za 15 dana all inclusive uTurskoj. Već prve noći boravka na odmoru moj osmogodišnji sin je osjećao mučninu i imao bolove u donjem dijelu stomaka. Obratio sam se hotelskom ljekaru koji je dijagnosticirao upalu slijepog crijeva te nas je uputio u lokalnu bolnicu gdje je izvršena operacija i odstranjenje slijepog crijeva. Nakon operacije dijete se je osjećalo dobro i već treći dan je predloženo da može napustiti bolnicu. Međutim, račun je bio 4.700 KM. Obzirom da sam platio all inclusive odmor, nisam ponio toliko novaca. Uprkos svim uvjeravanjima da ću platiti račun, nisu dozvolili otpust iz bolnice dok se ne plati račun. Sarajevo osiguranje je je za nekoliko sati organizovalo čovjeka koji je došao po mene u hotel te sam sa njim otišao u bolnicu i on je platio račun u moje ime gotovim novcem. Zahvaljujući polici putničkog zdravstvenog osiguranja ostatak godišnjeg odmora proveo sam bez neugodnosti."
        "Za vrijeme prevoza robe u Njemačku osjetio sam nestabilnost kamiona, zaustavio sam se na slijedećem parkingu i podvukao se pod kamion. U sljedećem trenutku eksplodirala je guma i ja sam izgubio svijest. Probudio sam se u bolnici i objasnili su mi da imam povredu oka i posjekotine na licu, te da je izvršena operacija oka. Pored pitanja koja sam sebi postavljao o svom zdravlju, pitao sam se kako ću ovo sve platiti? Na svu sreću imao sam policu putničkog zdravstvenog osiguranja te je Sarajevo osiguranje preuzelo sve troškove za moje liječenje koje neznam kako bi platio sam."
        "Za vrijeme godišnjeg odmora na Kipru iznajmio sam skuter. Obzirom da nisam baš iskusan u vožnji, udario sam sa skuterom u zid. Po mene su došla kola hitne pomoći i odvezli me u bolnicu. Konstatovali su otvoreni prelom butne kosti pa sam morao biti operisan odmah. Našao sam se u nezavidnoj situaciji, pogotovo pošto je bio zadnji dan aranžmana i moja grupa se vratila dok sam bio u bolnici. Brinuo sam se kako ću se vratiti kući obzirom da sam tek operisan i da mi je noga u gipsu i moram mirovati. Međutim Sarajevo osiguranje je organizovalo medicinski let gdje sam uz pratnju ljekara avionom prebačen u Sarajevo."
        "Moj suprug je putem firme otišao na rad u Ukrajinu. Nažalost pao je sa skele i posljedice su bile fatalne. Pored sve tuge i stresa bili smo zabrinuti kako ćemo prevesti tijelo mog supruga u BiH i ukopati ga prema tradiciji. Sarajevo osiguranje je organizovalo prevoz umrlog i svu administrativnu proceduru tako da je ukop izvršen već nakon 3 dana nakon smrti."
        "Neke stvari nemožemo spriječiti ali barem možemo ublažiti njihove posljedice!"
        "Sarajevo osiguranje nudi iz svoje palete osiguranja razne varijante polica putničkog zdravstvenog osiguranja, te smo sigurni da ćemo za Vaš profil naći najbolju ponudu kojom ćete biti zadovoljni i dobro osigurani!"
        "Kako bi uokvirili Vašu sigurnost za vrijeme boravka u inostranstvu uz osnovno Putničko zdravstveno osiguranje vam nudimo ostale varijante i dodatna osiguranja za:"
        "Otkaz putovanja"
        "Osiguranje prtljaga"
        "Osiguranje nezgode na putovanju"
        "Osiguranje odgovornosti na putovanju"
        "Dodatne ugodnosti možete ugovarati u našim podružnicama i prodajnim punktovima, dok sve ostale informacije možete dobiti putem e-maila pzo@sarajevoosiguranje.ba ili na telefone 061 266 680 i 061 489 999"
        "Vi živite mi brinemo!"
        "Vaše Sarajevo osiguranje",

];
